/***************************************************************************************************
FatBoy Engine -- errors

Purpose: registry of all error codes generated by the various functions and what they mean
new catagories and codes will be added as needed. error codes will be in the fbc_err namespace
***************************************************************************************************/

#pragma once

namespace fbc_err
{
	const int ERR_POOL_START = 1000;

	enum CODE
	{
		OK = 42, //success, this code is returned only upon successful execution of a function

		GEN_ERR_START = ERR_POOL_START,

			GENERIC_FAILURE, //a generic, non breaking error occured
			INIT_FAIL, //an initialization function has failed
			UNSUPORTED_SYSTEM, //compiled on an currently unsupported system
			FILE_LOAD_FAIL, //failure occured while loading a file
			ID_NOT_FOUND, //requested ID number not found, resource may need to be reloaded

		GEN_ERR_END,

		RENDER_ERROR_START, 
		
			FILE_UNLOAD_FAIL, //failure occured while deleteing a file from memory
			FILENAME_NOT_FOUND, //unable to find the file while loading
			D3D_FAIL, //the Direct3D system has failed to load on a Windows based machine
		
		RENDER_ERROR_END,

		LEGACY_RENDER_ERROR_START, //if any code in this range is thrown, problem exists with the legacy render class

			CALLNAME_NOT_FOUND, //could not find the callname (render v1 only: callnames eliminated in v2+)
			LEGACY_RENDER_FUNCTION_FAIL, //a legacy render function was called and failed to exicute properly

		LEGACY_RENDER_ERROR_END,

		INPUT_ERROR_START,

			INPUT_REGISTRATION_FAILURE, //failure occured while registering new input
			INPUT_NOT_FOUND, //input key was not found
			INPUT_NOT_SUPPORTED_BY_FUNCTION, //input was polled by the wrond function
			INPUT_NOT_INITIALIZED, //function failed due to uninitialized device, run initialize() before attempting

		INPUT_ERROR_END,

		SOUND_ERROR_START,

			FAILED_TO_LOAD_AUDIO_FILE, //the audio file failed to load, verify correct filename
			AUDIO_DEVICE_NOT_READY, //the sound device is not initialized
			UNABLE_TO_PLAY_FILE, //the specified file would not play
	
		SOUND_ERROR_END,

		FBC_ERR_END
	};
}